### ISSUE TITLE
dubbo应该是推荐TCP长连接的吧，这个有计划改掉吗？

### ISSUE THREAD

**Issue by yuzhigang33** [kaelzhang/node-dubbo#1]
现在你的实现是每次请求都建一个socket连接，是否考虑实现一个 KeepAlive agent

**Comment by kaelzhang** [comment]
现在还没开发 ok，下周部署到线上的时候，会包含 TCP 长连接 + 长连接池

**Comment by kaelzhang** [comment]
related to #6
