### ISSUE TITLE
目前是否还未发布完整包？

### ISSUE THREAD

**Issue by nbwgl** [kaelzhang/node-dubbo#2]
刚试了一下，在const Dubbo = require('dubbo');语句就挂住了，是不是因为还不是完整包？

**Comment by nbwgl** [comment]
对这个包比较有期待，我目前使用node-zookeeper-dubbo-wxx，有个局限是短连接，也不能注册多个服务。

**Comment by kaelzhang** [comment]
下周前

**Comment by kaelzhang** [comment]
duplicate with #1 , close for now.
